export const DISPATCH_COLUMNS = {
  SO_NO: 0,
  SKU_CODE: 1,
  CYCLE_ID: 2,
  PRODUCT: 3,
  DIVISION: 4,
  PRODUCTION_QTY: 5,
  RATE: 6,
  SHIPPING_LOCATION: 7,
  BILLING_LOCATION: 8,
  FREIGHT: 9,
  WASTAGE_QTY: 10,
  DISPATCH_QTY: 11,
  AVAILABLE_QTY: 12,
  STATUS: 13,
  CREATED_AT: 14,
  UPDATED_AT: 15,
};

export const DISPATCH_SHEET_COLUMNS = {
  DISPATCH_QTY: "L",
  AVAILABLE_QTY: "M",
  STATUS: "N",
  UPDATED_AT: "P"
};