export const DISPATCH_COLUMNS = {
  SO_NO: 0,
  SKU_CODE: 1,
  CYCLE_ID: 2,
  PRODUCT: 3,
  CUSTOMER:4,
  DRIVER_NAME:5,
  VEHICLE_NO:6,
  PARTY_PO:7,
  ROUTE:8,
   DIVISION: 9,
  PRODUCTION_QTY:10,
  RATE: 11,
  SHIPPING_LOCATION: 12,
  BILLING_LOCATION: 13,

  FREIGHT_CHARGES: 14, // YES / NO
  FREIGHT_RS: 15,     // Freight amount
  
  WASTAGE_QTY: 16,
  DISPATCH_QTY: 17,
  AVAILABLE_QTY: 18,
  STATUS: 19,
  CREATED_AT: 20,
  UPDATED_AT: 21,
};

export const DISPATCH_SHEET_COLUMNS = {
  DISPATCH_QTY: "R",
  AVAILABLE_QTY: "S",
  STATUS: "T",
  UPDATED_AT: "V"
};