// constants/productMap.js

export const PRODUCT_COLUMNS = {
  SKU: 0,
  PRODUCT_NAME: 1,
  DIVISION: 2,
  SIZE: 3,
  COLOR: 4,
  RATE:5,
  UNIT:6,
  METERPERROLL:7,
  METERPERKG:8,
  STATUS: 9,
  CREATED_BY: 10,
  CREATED_AT: 11,
  UPDATED_BY: 12,
  UPDATED_AT: 13,
};