
export const SHEET_NAMES = {
    PRODUCTION_SHEET:'Production_Process',
    SALES_MASTER:'Sales_order',
    DISPATCH_SHEET:'Dispatch_Sheets',
    WOVEN_STOCK:'FG_INVENTORY_MASTER',
    PRODUCT_SHEET:'PRODUCT_MASTER',
    INVENTORY_SHEET:'FG_INVENTORY_MASTER',
    USERS:"Users",
    NOTIFICATIONS:"Notifications",
    BILLING_SHEET:"BILLING_SHEET"
}



export const SHEETS_FROM_ENV_ID = {
    SALES_SHEET:process.env.GOOGLE_SHEET_ID,
    PRODUCTION_PROCESS_CROCHET:process.env.CROCHET_DATABASE_ID,
    PRODUCTION_PROCESS_WOVEN:process.env.WOVEN_DATABASE_ID,
    FG_INVENTORY_SHEET_ID:process.env.FG_INVENTORY_SHEET_ID,
    PRODUCT_MASTER_SHEET_ID:process.env.PRODUCT_MASTER_SHEET_ID,
}


