// WE WILL DO THIS FUNCTIONALLITY LATER


export const ALLOCATION_COLUMNS = {
  SO_NO: 0,
  SKU_CODE: 1,
  PRODUCT: 2,
  DIVISION: 3,
  UNIT: 4,
  CUSTOMER: 5,
  SO_QTY:6,
  FG_ALLOCATED_QTY:7,
  PRODUCTION_REQUIRED_QTY:8,
  CYCLE_ID: 8,
  ALLOCATION_STATUS: 9,
  CREATED_AT: 10,
};