
// USER SHEET COLUMNS 
export const USER_COLUMNS = {
    NAME:0,
    ROLE:1,
    DIVISION:2,
    PASSWORD:3,
    STATUS:4,
    USER_ID:5
}

// PUSH SUBSCRIPTION COLUMNS 
export const SUBSCRIPTION_COLUMNS = {
  SUBSCRIPTION_ID: 0,
  USER_ID: 1,
  USER_NAME: 2,
  ROLE: 3,
  DIVISION: 4,
  ENDPOINT: 5,
  P256DH: 6,
  AUTH: 7,
  DEVICE_NAME: 8,
  IP_ADDRESS: 9,
  CREATED_AT: 10,
  UPDATED_AT: 11,
  STATUS: 12,
};